name: 'Jira Issue Key Checker'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: actions/checkout@v3
        with:
          commits: ${{ github.event.commits.message }}

      - name: Check if the commit message contains a jira ticket
        uses: actions/checkout@v3
        with:
          commits: ${{ github.event.commits.message }}
          pattern: '^(EC|SRE)-[0-9]+\s'
          echo: ${{ github.event.commits.message }}
          error: 'Commit message does not contain a Jira ticket!'
          
 

